#!/bin/bash

TITLE=$1
EXCERPT=$2  # optional
TITLEF=$(echo $TITLE | tr " " "-")
YEAR=$(date +"%Y")
MONTH=$(date +"%m")

mkdir -p "src/posts/$YEAR/$MONTH"
FILENAME="src/posts/$YEAR/$MONTH/$TITLEF.md"

cat <<EOF > $FILENAME
---
title: "$TITLE"
published: false
date: "$(date '+%Y-%m-%d')"
tags:
-
---
$EXCERPT
<!-- excerpt -->

EOF

echo "Created new post at $FILENAME"
